import { Input } from "@ggpx/ui";
import { type NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mx-auto flex flex-col items-center justify-center md:h-screen">
        <div className="sm:max-w-md">
          <Input type="text" placeholder="yo" />
        </div>
      </main>
    </>
  );
};

export default Home;
